=begin
#KORONA.cloud API v3

#Our api provides access to our cloud services

OpenAPI spec version: 3
Contact: support@combase.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaClient::ReceiptsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReceiptsApi' do
  before do
    # run before each test
    @instance = KoronaClient::ReceiptsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReceiptsApi' do
    it 'should create an instance of ReceiptsApi' do
      expect(@instance).to be_instance_of(KoronaClient::ReceiptsApi)
    end
  end

  # unit tests for get_receipt
  # lists a single receipt
  # 
  # @param korona_account_id the account id
  # @param receipt_id the id of the receipt
  # @param [Hash] opts the optional parameters
  # @return [Receipt]
  describe 'get_receipt test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_receipts
  # lists all receipts
  # 
  # @param korona_account_id the account id
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page number of the page to fetch
  # @option opts [Integer] :size amount of objects to return per page
  # @option opts [String] :sort attribute to sort by (multiple separated by comma; max. 5)
  # @option opts [Integer] :revision last revision number, objects with a greater revision than this will be returned
  # @option opts [String] :point_of_sale point of sale
  # @option opts [String] :organizational_unit organizational unit
  # @option opts [Integer] :z_count z-count of the receipt
  # @option opts [DateTime] :min_create_time min (inclusive) create time of the receipt (ISO 8601; date, time and timezone)
  # @option opts [DateTime] :max_create_time max (inclusive) create time of the receipt (ISO 8601; date, time and timezone)
  # @return [ResultListReceipt]
  describe 'get_receipts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
