=begin
#KORONA.cloud API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 2.17.26
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::PaymentServiceConfiguration
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::PaymentServiceConfiguration do
  let(:instance) { KoronaCloudClient::PaymentServiceConfiguration.new }

  describe 'test an instance of PaymentServiceConfiguration' do
    it 'should create an instance of PaymentServiceConfiguration' do
      expect(instance).to be_instance_of(KoronaCloudClient::PaymentServiceConfiguration)
    end
  end
  describe 'test attribute "merchant_site_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "merchant_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "merchant_key"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "device_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "service_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CASH", "DEFAULT_PAYMENT_TYPE", "MERCHANTWARE", "MERCURY", "LEGACY_ZVT", "KORONA_PREPAID", "CREDIT_AUTHORIZATION_TERMINAL"])
      # validator.allowable_values.each do |value|
      #   expect { instance.service_type = value }.not_to raise_error
      # end
    end
  end

end
