=begin
#KORONA.cloud API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.2-SNAPSHOT
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::PeriodRevenueDataRevenueData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::PeriodRevenueDataRevenueData do
  let(:instance) { KoronaCloudClient::PeriodRevenueDataRevenueData.new }

  describe 'test an instance of PeriodRevenueDataRevenueData' do
    it 'should create an instance of PeriodRevenueDataRevenueData' do
      expect(instance).to be_instance_of(KoronaCloudClient::PeriodRevenueDataRevenueData)
    end
  end
  describe 'test attribute "start"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "_end"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "results"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
