=begin
#KORONA.cloud API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 2.19.20
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::PromotionBenefitExtendedDiscountPositionSelectionCriteriaMinMaxRangeValueComperator
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::PromotionBenefitExtendedDiscountPositionSelectionCriteriaMinMaxRangeValueComperator do
  let(:instance) { KoronaCloudClient::PromotionBenefitExtendedDiscountPositionSelectionCriteriaMinMaxRangeValueComperator.new }

  describe 'test an instance of PromotionBenefitExtendedDiscountPositionSelectionCriteriaMinMaxRangeValueComperator' do
    it 'should create an instance of PromotionBenefitExtendedDiscountPositionSelectionCriteriaMinMaxRangeValueComperator' do
      expect(instance).to be_instance_of(KoronaCloudClient::PromotionBenefitExtendedDiscountPositionSelectionCriteriaMinMaxRangeValueComperator)
    end
  end
  describe 'test attribute "exclusive"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
