=begin
#KORONA.cloud API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 2.17.26
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::PromotionBenefitExtendedDiscountPositionSelectionCriteria
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::PromotionBenefitExtendedDiscountPositionSelectionCriteria do
  let(:instance) { KoronaCloudClient::PromotionBenefitExtendedDiscountPositionSelectionCriteria.new }

  describe 'test an instance of PromotionBenefitExtendedDiscountPositionSelectionCriteria' do
    it 'should create an instance of PromotionBenefitExtendedDiscountPositionSelectionCriteria' do
      expect(instance).to be_instance_of(KoronaCloudClient::PromotionBenefitExtendedDiscountPositionSelectionCriteria)
    end
  end
  describe 'test attribute "amount_range"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "max_iterations"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "price_range"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "selections"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
