=begin
#KORONA.cloud API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.1.64
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::TooManyRequestsErrorModel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::TooManyRequestsErrorModel do
  let(:instance) { KoronaCloudClient::TooManyRequestsErrorModel.new }

  describe 'test an instance of TooManyRequestsErrorModel' do
    it 'should create an instance of TooManyRequestsErrorModel' do
      expect(instance).to be_instance_of(KoronaCloudClient::TooManyRequestsErrorModel)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["DAILY_LIMIT_EXCEEDED", "TOO_MANY_PARALLEL_UPDATE_REQUESTS"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

end
