# -*- encoding: utf-8 -*-

=begin
#KORONA.cloud API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 2.17.26
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "korona-cloud-client/version"

Gem::Specification.new do |s|
  s.name        = "korona-cloud-client"
  s.version     = KoronaCloudClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["support@combase.net"]
  s.homepage    = "https://github.com/giantmonkey/korona-cloud-client"
  s.summary     = "KORONA.cloud API v3 Ruby Gem"
  s.description = "Our api provides access to our cloud services"
  s.license     = "Unlicense"
  s.required_ruby_version = ">=2.3.8"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
